<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  
  <ItemGroup>
    <!-- API Versioning -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />

    <!-- Analyzers -->
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />

    <!-- Test Libraries -->
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />

      <!-- MediatR -->
      <PackageVersion Include="MediatR" Version="12.5.0" />
  </ItemGroup>
</Project>