services:
  support-app-api:
    container_name: support-app-api
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=.;Database=support-app-sqlserver;Trusted_Connection=True;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - support-app-net
    restart: on-failure

  sqlserver:
    container_name: support-app-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password1
    ports:
      - "14333:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - support-app-net
    restart: always

volumes:
  sqlserver-data: {}

networks:
  support-app-net:
    driver: bridge
