<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <!-- documentation -->
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" /> 
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SupportApp.Application\SupportApp.Application.csproj" />
    <ProjectReference Include="..\SupportApp.Infrastructure\SupportApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
