@HostAddress = https://localhost:7093

###
GET {{HostAddress}}
Accept: application/json

### GET categories
GET {{HostAddress}}/api/categories
Accept: application/json

### POST categories
POST {{HostAddress}}/api/lookup/categories
Accept: application/json

### PUT categories
PUT {{HostAddress}}/api/lookup/categories/1
Accept: application/json

### DELETE categories
DELETE {{HostAddress}}/api/lookup/categories/1
Accept: application/json

### Register
POST {{HostAddress}}/api/auth/clients/register
Content-Type: application/json
{
    "email": "aya@client.com",
    "password": "john.labor@localhost",
    "phoneNumber" : 0592309501,
    "name": "aya"
}

### Login
POST {{HostAddress}}/api/auth/clients/login
Content-Type: application/json
{
    "email": "aya@client.com",
    "password": "john.labor@localhost",
}

### Refresh Token
POST {{baseUrl}}/token/refresh-token
Content-Type: application/json

{
    "ExpiredAccessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOWE1OTEyOS02YzIwLTQxN2EtODM0ZC0xMWEyMDhkMzJkOTYiLCJyb2xlIjoiTWFuYWdlciIsIm5iZiI6MTc0MDQzNDgwNSwiZXhwIjoxNzQwNDM4NDA1LCJpYXQiOjE3NDA0MzQ4MDUsImlzcyI6ImxvY2FsaG9zdCIsImF1ZCI6ImxvY2FsaG9zdCJ9.EOUXvigbhiC2a2RMpEHt-bfbDduC8034xnELEQRdRM0",
    "refreshToken": "Byg+Wlkvk4iJ0MdNTI4KJ62Ec9SMcijkQXplN8Vs9L0="
}

### Profile
POST {{HostAddress}}/api/auth/me
Content-Type: application/json
{
    "email": "aya@client.com",
    "password": "aya@client.com",
    "phoneNumber" : 0592309501,
    "name": "aya"
}

### Employees (Paginated)
Get {{HostAddress}}/api/employees
Content-Type: application/json


### Create Employee
POST {{HostAddress}}/api/employees
Content-Type: application/json
{
    "email": "aya@employee.com",
    "password": "aya@employee.com",
    "phoneNumber" : 0592309503,
    "name": "Eng aya",
    "role" : "Admin"
}

### Update Employee
Put {{HostAddress}}/api/employees/1
Content-Type: application/json
{
    "email": "aya@employee.com",
    "password": "aya@employee.com",
    "phoneNumber" : 0592309503,
    "name": "Eng aya",
    "role" : "Admin"
}

### Delete Employee
DELETE {{HostAddress}}/api/employees/1
Content-Type: application/json

### Tickets (Paginated)
Get {{HostAddress}}/api/tickets
Content-Type: application/json

### Tickets (details)
Get {{HostAddress}}/api/tickets/1
Content-Type: application/json


### Create ticket
POST {{HostAddress}}/api/tickets
Content-Type: application/json
{
    "client_id": "",
}

### Assign Employee to ticket
POST {{HostAddress}}/api/tickets/1/assign
Content-Type: application/json
{
    "user_id": "",
}


### update ticket status
PUT {{HostAddress}}/api/tickets/1
Content-Type: application/json
{
    "statsu": "2",
}

### Ticket Reply (Admin $ client)
POST {{HostAddress}}/api/tickets/1/reply
Content-Type: application/json
{
    "message": "",
    "attachments" : []
}