using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

using SupportApp.Application.Common.Interfaces;
using SupportApp.Application.Features.Tickets.Dtos;

namespace SupportApp.Infrastructure.Pdf
{
    public sealed class TicketPdfRenderer : IPdfRenderer
    {
        public async Task<FileResponse> RenderTicketAsync(TicketDto ticket, CancellationToken ct)
        {
            var doc = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    page.Header().Element(BuildHeader(ticket));
                    page.Content().Element(BuildContent(ticket));
                    page.Footer().Element(BuildFooter());
                });
            });

            return new FileResponse
            {
                FileName = $"Ticket_{ticket.Number}.pdf",
                ContentType = "application/pdf",
                Bytes = doc.GeneratePdf()
            };
        }

        // ===================== Header =====================
        private static Action<IContainer> BuildHeader(TicketDto ticket) => header =>
        {
            header.Column(col =>
            {
                col.Item().Row(row =>
                {
                    row.RelativeItem().AlignMiddle().Column(hc =>
                    {
                        hc.Item().Text($"Ticket Report #{ticket.Number}")
                                 .FontSize(20).SemiBold().FontColor(Colors.Grey.Darken3);
                        hc.Item().Text($"Title: {ticket.Title}");
                        hc.Item().Text($"Category: {ticket.Category?.Title ?? "N/A"}");
                        hc.Item().Text($"Priority: {ticket.Priority}   •   Status: {ticket.Status}");
                    });

                    row.RelativeItem().AlignRight().Column(rc =>
                    {
                        rc.Item().Text($"Reporter: {ticket.Owner?.Name ?? "N/A"}");
                        rc.Item().Text($"Assignee: {ticket.Assignee?.Name ?? "N/A"}");
                        rc.Item().Text($"Opened: {ticket.OpenedAt:yyyy-MM-dd HH:mm}");
                        if (ticket.ClosedAt != default)
                            rc.Item().Text($"Closed: {ticket.ClosedAt:yyyy-MM-dd HH:mm}");
                    });
                });

                col.Item().PaddingVertical(14)
                          .LineHorizontal(2)
                          .LineColor(Colors.Grey.Darken2);
            });
        };

        // ===================== Content (no attachments) =====================
        private static Action<IContainer> BuildContent(TicketDto ticket) => content =>
        {
            content.Column(col =>
            {
                // Details
                col.Item().Text("Details").FontSize(14).SemiBold().FontColor(Colors.Grey.Darken2);
                col.Item().Text(ticket.Description ?? string.Empty);

                col.Item().PaddingTop(12).LineHorizontal(1).LineColor(Colors.Grey.Lighten1);

                // Activities
                col.Item().PaddingTop(10).Text("Activities").FontSize(14).SemiBold().FontColor(Colors.Grey.Darken2);

                if (ticket.Activities is null || ticket.Activities.Count == 0)
                {
                    col.Item().PaddingTop(6).Text("No activities yet.").Italic().FontColor(Colors.Grey.Medium);
                    return;
                }

                foreach (var act in ticket.Activities)
                {
                    col.Item().PaddingVertical(8).Element(e => BuildActivity(act)(e));
                }
            });
        };

        private static Action<IContainer> BuildActivity(TicketActivityDto act) => activity =>
        {
            activity.Column(aCol =>
            {
                aCol.Item().Text($"Type: {act.Type?.ToString() ?? "N/A"}");
                aCol.Item().Text($"By: {act.Creator?.Name ?? "Unknown"}   •   At: {act.CreatedAtUtc:yyyy-MM-dd HH:mm}");

                if (!string.IsNullOrWhiteSpace(act.Description))
                    aCol.Item().Text($"Description: {act.Description}");

                aCol.Item().PaddingTop(8).LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten1);
            });
        };

        // ===================== Footer =====================
        private static Action<IContainer> BuildFooter() => footer =>
        {
            footer.Row(row =>
            {
                row.RelativeItem().AlignLeft()
                   .Text("Generated by SupportApp").FontSize(9).FontColor(Colors.Grey.Medium);

                row.RelativeItem().AlignRight()
                   .Text($"{DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC").FontSize(9).FontColor(Colors.Grey.Medium);
            });
        };
    }
}
